name: Allure Report CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '22'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Verify Gradle Wrapper
        run: |
          ls -R gradle
          test -f gradle/wrapper/gradle-wrapper.jar

      - name: Run tests
        run: ./gradlew clean test

      - name: Verify Allure Results
        if: always()
        run: |
          find . -type d -name "allure-results"
          ls -R build/allure-results

      - name: Checkout GitHub Pages
        if: always()
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: justin-gh-pages
          path: justin-gh-pages

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          gh_pages: justin-gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: justin-gh-pages
          publish_dir: allure-history